version: "3.8"
services:
  nextjs-app:
    image: test-nextjs-image
    container_name: test-nextjs-container
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
